version: "3.9"

services:
  fastapi:
    build: .
    container_name: readnet_service
    ports:
      - "8000:8000"

    volumes:
      - .:/backend
      - /backend/.venv

    working_dir: /backend

    command: uv run uvicorn server:app --reload --host 0.0.0.0 --port 8000

    env_file:
      - .env

    restart: unless-stopped
